# GitHub Pages Jekyll Configuration
# This ensures .well-known directory is included

include:
  - .well-known
  - .nojekyll

# Exclude unnecessary files
exclude:
  - README.md
  - build-android.sh
  - server.js
  - package.json
  - node_modules

# Disable Jekyll processing for better compatibility
plugins: []
markdown: kramdown
highlighter: rouge