name: Build Android AAB

on:
  push:
    branches: [prod]
    tags: ['v*']
  pull_request:
    branches: [prod]
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'adopt'
        java-version: '17'
        
    - name: Install dependencies
      run: |
        npm install -g @bubblewrap/cli
        npm install -g pwabuilder
        
    - name: Create build directories
      run: |
        mkdir -p android-build
        mkdir -p aab-output
        
    - name: Build with Bubblewrap
      run: |
        cd android-build
        bubblewrap init --manifest https://hoanganh25991.github.io/tank-adventure/manifest.json
        bubblewrap build --skipPwaValidation
        cp *.aab ../aab-output/ || echo "No AAB files found"
        cd ..
        
    - name: Build with PWABuilder
      run: |
        pwabuilder https://hoanganh25991.github.io/tank-adventure \
          -p android \
          -d ./pwabuilder-output \
          -s "Tank Adventure" \
          -l info
        
    - name: List generated files
      run: |
        echo "=== AAB Output Directory ==="
        ls -la aab-output/ || echo "No AAB files"
        echo "=== PWABuilder Output Directory ==="
        find pwabuilder-output/ -name "*.aab" -o -name "*.apk" || echo "No Android files found"
        
    - name: Upload AAB artifacts
      uses: actions/upload-artifact@v4
      with:
        name: android-aab-${{ github.run_number }}
        path: |
          aab-output/*.aab
          pwabuilder-output/**/android/*.aab
        if-no-files-found: warn
        
    - name: Upload build logs
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: build-logs-${{ github.run_number }}
        path: |
          android-build/
          pwabuilder-output/
        if-no-files-found: warn

  # Job for signed release builds (only on tags)
  build-release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    needs: build-android
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'adopt'
        java-version: '17'
        
    - name: Install Bubblewrap
      run: npm install -g @bubblewrap/cli
      
    - name: Decode signing key
      env:
        KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
      run: |
        echo "$KEYSTORE_BASE64" | base64 -d > tank-adventure-release.keystore
        
    - name: Build signed AAB
      env:
        KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
        KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
      run: |
        bubblewrap init --manifest https://hoanganh25991.github.io/tank-adventure/manifest.json
        bubblewrap build \
          --skipPwaValidation \
          --signingKeyPath ./tank-adventure-release.keystore \
          --signingKeyPassword "$KEYSTORE_PASSWORD" \
          --signingKeyAlias "$KEY_ALIAS"
        
    - name: Upload signed AAB
      uses: actions/upload-artifact@v4
      with:
        name: android-aab-signed-${{ github.ref_name }}
        path: '*.aab'
        
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: '*.aab'
        draft: true
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}